import React from 'react'
import Head from 'next/head'

type Props = {
    children: JSX.Element
}

export const Layout = ({children}: Props) => {
  return (
    <>
    <Head>
        <title>DevBook</title>
        <meta name="description" content="Generated by create next app" />
    </Head>
    <main>
        {children}
    </main>
    <footer>
        Copyright Ostre-Dymy Inc.<br/>
        All rights reserved
    </footer>
</>
  )
}
