import React, { useState } from "react";
import Head from "next/head";
import { Burger } from "./Burger";
import Image from "next/image";

type Props = {
  children: JSX.Element;
};

export const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>DevBook</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="crossorigin"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@200;300;400;500;600;700;800;900&family=Oleo+Script+Swash+Caps&display=swap"
          rel="stylesheet"
        />
      </Head>
      <nav className="fixed flex items-center justify-between w-full h-20 p-4 bg-white shadow-xl">
        <h1 className="text-4xl text-brand-rebbecca">
          DevBook
        </h1>
        <div className="flex items-center">
          <Image
            className="rounded-full"
            src="/foteczka.jpeg"
            width={50}
            height={50}
          />
          <Burger />
        </div>
      </nav>
      <main className="min-h-[93vh] pt-32">
        {children}
      </main>
      <footer className="min-h-[7vh] text-center">
        Copyright Ostre-Dymy Inc.
        <br />
        All rights reserved
      </footer>
    </>
  );
};
